#!/bin/bash
sudo -i
wget https://raw.githubusercontent.com/hitman-045/jenkinsjava/master/java.sh 
wget https://raw.githubusercontent.com/hitman-045/jenkinsjava/master/jenkins.sh
chmod +x java.sh
chmod +x jenkins.sh
./java.sh
source /etc/profile
./jenkins.
